# Student Alcohol Consumption

### Step 1. Import the necessary libraries

In [21]:
import pandas as pd
import numpy as np

### Step 2. Import the datasets *student-mat* and *student-por* and merge them.

In [22]:
student_mat = pd.read_csv("Exercise Data Files/Pandas Exercise Lambda Functions Files/student-mat.csv")
student_mat

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15
10,GP,F,15,U,GT3,T,4,4,teacher,health,...,3,3,3,1,2,2,0,10,8,9
11,GP,F,15,U,GT3,T,2,1,services,other,...,5,2,2,1,1,4,4,10,12,12
12,GP,M,15,U,LE3,T,4,4,health,services,...,4,3,3,1,3,5,2,14,14,14
13,GP,M,15,U,GT3,T,4,3,teacher,other,...,5,4,3,1,2,3,2,10,10,11
14,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,16,16
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,4,4,1,2,2,4,14,14,14
16,GP,F,16,U,GT3,T,4,4,services,services,...,3,2,3,1,2,2,6,13,14,14
17,GP,F,16,U,GT3,T,3,3,other,other,...,5,3,2,1,1,4,4,8,10,10
18,GP,M,17,U,GT3,T,3,2,services,services,...,5,5,5,2,4,5,16,6,5,5
19,GP,M,16,U,LE3,T,4,3,health,other,...,3,1,3,1,3,5,4,8,10,10
20,GP,M,15,U,GT3,T,4,3,teacher,other,...,4,4,1,1,1,1,0,13,14,15
21,GP,M,15,U,GT3,T,4,4,health,health,...,5,4,2,1,1,5,0,12,15,15
22,GP,M,16,U,LE3,T,4,2,teacher,other,...,4,5,1,1,3,5,2,15,15,16
23,GP,M,16,U,LE3,T,2,2,other,other,...,5,4,4,2,4,5,0,13,13,12
24,GP,F,15,R,GT3,T,2,4,services,health,...,4,3,2,1,1,5,2,10,9,8
25,GP,F,16,U,GT3,T,2,2,services,services,...,1,2,2,1,3,5,14,6,9,8
26,GP,M,15,U,GT3,T,2,2,other,other,...,4,2,2,1,2,5,2,12,12,11
27,GP,M,15,U,GT3,T,4,2,health,services,...,2,2,4,2,4,1,4,15,16,15
28,GP,M,16,U,LE3,A,3,4,services,other,...,5,3,3,1,1,5,4,11,11,11
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,4,4,5,5,5,5,16,10,12,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,MS,M,18,R,GT3,T,1,3,at_home,other,...,3,3,4,2,4,3,4,10,10,10
366,MS,M,18,U,LE3,T,4,4,teacher,services,...,4,2,2,2,2,5,0,13,13,13
367,MS,F,17,R,GT3,T,1,1,other,services,...,5,2,1,1,2,1,0,7,6,0
368,MS,F,18,U,GT3,T,2,3,at_home,services,...,5,2,3,1,2,4,0,11,10,10
369,MS,F,18,R,GT3,T,4,4,other,teacher,...,3,2,2,4,2,5,10,14,12,11
370,MS,F,19,U,LE3,T,3,2,services,services,...,3,2,2,1,1,3,4,7,7,9
371,MS,M,18,R,LE3,T,1,2,at_home,services,...,4,3,3,2,3,3,3,14,12,12
372,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,13,11,11
373,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,14,6,5,5
374,MS,F,18,R,LE3,T,4,4,other,other,...,5,4,4,1,1,1,0,19,18,19
375,MS,F,18,R,GT3,T,1,1,other,other,...,4,3,2,1,2,4,2,8,8,10
376,MS,F,20,U,GT3,T,4,2,health,other,...,5,4,3,1,1,3,4,15,14,15
377,MS,F,18,R,LE3,T,4,4,teacher,services,...,5,4,3,3,4,2,4,8,9,10
378,MS,F,18,U,GT3,T,3,3,other,other,...,4,1,3,1,2,1,0,15,15,15
379,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,17,10,10,10
380,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,15,14,14
381,MS,M,18,R,GT3,T,2,1,other,other,...,4,4,3,1,3,5,5,7,6,7
382,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,2,11,11,10
383,MS,M,19,R,GT3,T,1,1,other,services,...,4,3,2,1,3,5,0,6,5,0
384,MS,M,18,R,GT3,T,4,2,other,other,...,5,4,3,4,3,3,14,6,5,5
385,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,2,10,9,10
386,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,4,4,3,2,2,5,7,6,5,6
387,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,0,7,5,0
388,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,0,7,9,8
389,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,0,6,5,0
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [23]:
student_por = pd.read_csv("Exercise Data Files/Pandas Exercise Lambda Functions Files/student-por.csv")
student_por

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,6,12,12,13
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,13,12,13
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,2,10,13,13
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,15,16,17
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,12,12,13
10,GP,F,15,U,GT3,T,4,4,teacher,health,...,3,3,3,1,2,2,2,14,14,14
11,GP,F,15,U,GT3,T,2,1,services,other,...,5,2,2,1,1,4,0,10,12,13
12,GP,M,15,U,LE3,T,4,4,health,services,...,4,3,3,1,3,5,0,12,13,12
13,GP,M,15,U,GT3,T,4,3,teacher,other,...,5,4,3,1,2,3,0,12,12,13
14,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,14,15
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,4,4,1,2,2,6,17,17,17
16,GP,F,16,U,GT3,T,4,4,services,services,...,3,2,3,1,2,2,10,13,13,14
17,GP,F,16,U,GT3,T,3,3,other,other,...,5,3,2,1,1,4,2,13,14,14
18,GP,M,17,U,GT3,T,3,2,services,services,...,5,5,5,2,4,5,2,8,8,7
19,GP,M,16,U,LE3,T,4,3,health,other,...,3,1,3,1,3,5,6,12,12,12
20,GP,M,15,U,GT3,T,4,3,teacher,other,...,4,4,1,1,1,1,0,12,13,14
21,GP,M,15,U,GT3,T,4,4,health,health,...,5,4,2,1,1,5,0,11,12,12
22,GP,M,16,U,LE3,T,4,2,teacher,other,...,4,5,1,1,3,5,0,12,13,14
23,GP,M,16,U,LE3,T,2,2,other,other,...,5,4,4,2,4,5,2,10,10,10
24,GP,F,15,R,GT3,T,2,4,services,health,...,4,3,2,1,1,5,2,10,11,10
25,GP,F,16,U,GT3,T,2,2,services,services,...,1,2,2,1,3,5,6,10,11,12
26,GP,M,15,U,GT3,T,2,2,other,other,...,4,2,2,1,2,5,8,11,12,12
27,GP,M,15,U,GT3,T,4,2,health,services,...,2,2,4,2,4,1,0,11,11,11
28,GP,M,16,U,LE3,A,3,4,services,other,...,5,3,3,1,1,5,2,12,12,13
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,4,4,5,5,5,5,4,12,11,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
619,MS,F,18,U,GT3,T,3,3,services,services,...,4,3,2,1,3,3,6,13,12,13
620,MS,F,17,U,LE3,T,4,4,at_home,at_home,...,2,3,4,1,1,1,4,15,14,15
621,MS,F,17,R,GT3,T,1,2,other,services,...,3,2,2,1,2,3,0,13,13,13
622,MS,M,18,R,GT3,T,1,3,at_home,other,...,3,3,4,2,4,3,0,8,10,9
623,MS,M,18,U,LE3,T,4,4,teacher,services,...,4,2,2,2,2,5,0,15,16,16
624,MS,F,17,R,GT3,T,1,1,other,services,...,5,2,1,1,2,1,0,8,8,9
625,MS,F,18,U,GT3,T,2,3,at_home,services,...,5,2,3,1,2,4,0,10,10,10
626,MS,F,18,R,GT3,T,4,4,other,teacher,...,3,2,2,4,2,5,0,7,5,0
627,MS,M,18,R,LE3,T,1,2,at_home,services,...,4,3,3,2,3,3,3,9,10,10
628,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,10,11,12
629,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,4,7,8,9
630,MS,F,18,R,LE3,T,4,4,other,other,...,5,4,4,1,1,1,0,15,17,17
631,MS,F,18,R,GT3,T,1,1,other,other,...,4,3,2,1,2,4,4,10,11,12
632,MS,F,19,R,GT3,T,1,1,at_home,other,...,4,3,3,1,1,3,4,7,8,9
633,MS,F,18,R,LE3,T,4,4,teacher,services,...,5,4,3,3,4,2,1,13,14,14
634,MS,F,18,U,GT3,T,3,3,other,other,...,4,1,3,1,2,1,1,16,16,16
635,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,10,8,9,9
636,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,17,18,19
637,MS,M,18,R,GT3,T,2,1,other,other,...,4,4,3,1,3,5,0,7,7,0
638,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,4,14,15,16
639,MS,M,19,R,GT3,T,1,1,other,services,...,4,3,2,1,3,5,0,5,8,0
640,MS,M,18,R,GT3,T,4,2,other,other,...,5,4,3,4,3,3,0,7,7,0
641,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,0,14,17,15
642,MS,F,17,U,GT3,T,4,3,teacher,other,...,5,5,4,1,1,1,0,6,9,11
643,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,4,4,3,2,2,5,4,7,9,10
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [31]:
pd.concat([student_mat,student_por],axis=0).reset_index(drop=True)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15
10,GP,F,15,U,GT3,T,4,4,teacher,health,...,3,3,3,1,2,2,0,10,8,9
11,GP,F,15,U,GT3,T,2,1,services,other,...,5,2,2,1,1,4,4,10,12,12
12,GP,M,15,U,LE3,T,4,4,health,services,...,4,3,3,1,3,5,2,14,14,14
13,GP,M,15,U,GT3,T,4,3,teacher,other,...,5,4,3,1,2,3,2,10,10,11
14,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,16,16
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,4,4,1,2,2,4,14,14,14
16,GP,F,16,U,GT3,T,4,4,services,services,...,3,2,3,1,2,2,6,13,14,14
17,GP,F,16,U,GT3,T,3,3,other,other,...,5,3,2,1,1,4,4,8,10,10
18,GP,M,17,U,GT3,T,3,2,services,services,...,5,5,5,2,4,5,16,6,5,5
19,GP,M,16,U,LE3,T,4,3,health,other,...,3,1,3,1,3,5,4,8,10,10
20,GP,M,15,U,GT3,T,4,3,teacher,other,...,4,4,1,1,1,1,0,13,14,15
21,GP,M,15,U,GT3,T,4,4,health,health,...,5,4,2,1,1,5,0,12,15,15
22,GP,M,16,U,LE3,T,4,2,teacher,other,...,4,5,1,1,3,5,2,15,15,16
23,GP,M,16,U,LE3,T,2,2,other,other,...,5,4,4,2,4,5,0,13,13,12
24,GP,F,15,R,GT3,T,2,4,services,health,...,4,3,2,1,1,5,2,10,9,8
25,GP,F,16,U,GT3,T,2,2,services,services,...,1,2,2,1,3,5,14,6,9,8
26,GP,M,15,U,GT3,T,2,2,other,other,...,4,2,2,1,2,5,2,12,12,11
27,GP,M,15,U,GT3,T,4,2,health,services,...,2,2,4,2,4,1,4,15,16,15
28,GP,M,16,U,LE3,A,3,4,services,other,...,5,3,3,1,1,5,4,11,11,11
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,4,4,5,5,5,5,16,10,12,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,MS,F,18,U,GT3,T,3,3,services,services,...,4,3,2,1,3,3,6,13,12,13
1015,MS,F,17,U,LE3,T,4,4,at_home,at_home,...,2,3,4,1,1,1,4,15,14,15
1016,MS,F,17,R,GT3,T,1,2,other,services,...,3,2,2,1,2,3,0,13,13,13
1017,MS,M,18,R,GT3,T,1,3,at_home,other,...,3,3,4,2,4,3,0,8,10,9
1018,MS,M,18,U,LE3,T,4,4,teacher,services,...,4,2,2,2,2,5,0,15,16,16
1019,MS,F,17,R,GT3,T,1,1,other,services,...,5,2,1,1,2,1,0,8,8,9
1020,MS,F,18,U,GT3,T,2,3,at_home,services,...,5,2,3,1,2,4,0,10,10,10
1021,MS,F,18,R,GT3,T,4,4,other,teacher,...,3,2,2,4,2,5,0,7,5,0
1022,MS,M,18,R,LE3,T,1,2,at_home,services,...,4,3,3,2,3,3,3,9,10,10
1023,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,10,11,12
1024,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,4,7,8,9
1025,MS,F,18,R,LE3,T,4,4,other,other,...,5,4,4,1,1,1,0,15,17,17
1026,MS,F,18,R,GT3,T,1,1,other,other,...,4,3,2,1,2,4,4,10,11,12
1027,MS,F,19,R,GT3,T,1,1,at_home,other,...,4,3,3,1,1,3,4,7,8,9
1028,MS,F,18,R,LE3,T,4,4,teacher,services,...,5,4,3,3,4,2,1,13,14,14
1029,MS,F,18,U,GT3,T,3,3,other,other,...,4,1,3,1,2,1,1,16,16,16
1030,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,10,8,9,9
1031,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,17,18,19
1032,MS,M,18,R,GT3,T,2,1,other,other,...,4,4,3,1,3,5,0,7,7,0
1033,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,4,14,15,16
1034,MS,M,19,R,GT3,T,1,1,other,services,...,4,3,2,1,3,5,0,5,8,0
1035,MS,M,18,R,GT3,T,4,2,other,other,...,5,4,3,4,3,3,0,7,7,0
1036,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,0,14,17,15
1037,MS,F,17,U,GT3,T,4,3,teacher,other,...,5,5,4,1,1,1,0,6,9,11
1038,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,4,4,3,2,2,5,4,7,9,10
1039,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
1040,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
1041,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
1042,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
1043,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

### Step 3. Assign it to a variable called df.

In [32]:
df=pd.concat([student_mat,student_por],axis=0).reset_index(drop=True)
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15
10,GP,F,15,U,GT3,T,4,4,teacher,health,...,3,3,3,1,2,2,0,10,8,9
11,GP,F,15,U,GT3,T,2,1,services,other,...,5,2,2,1,1,4,4,10,12,12
12,GP,M,15,U,LE3,T,4,4,health,services,...,4,3,3,1,3,5,2,14,14,14
13,GP,M,15,U,GT3,T,4,3,teacher,other,...,5,4,3,1,2,3,2,10,10,11
14,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,16,16
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,4,4,1,2,2,4,14,14,14
16,GP,F,16,U,GT3,T,4,4,services,services,...,3,2,3,1,2,2,6,13,14,14
17,GP,F,16,U,GT3,T,3,3,other,other,...,5,3,2,1,1,4,4,8,10,10
18,GP,M,17,U,GT3,T,3,2,services,services,...,5,5,5,2,4,5,16,6,5,5
19,GP,M,16,U,LE3,T,4,3,health,other,...,3,1,3,1,3,5,4,8,10,10
20,GP,M,15,U,GT3,T,4,3,teacher,other,...,4,4,1,1,1,1,0,13,14,15
21,GP,M,15,U,GT3,T,4,4,health,health,...,5,4,2,1,1,5,0,12,15,15
22,GP,M,16,U,LE3,T,4,2,teacher,other,...,4,5,1,1,3,5,2,15,15,16
23,GP,M,16,U,LE3,T,2,2,other,other,...,5,4,4,2,4,5,0,13,13,12
24,GP,F,15,R,GT3,T,2,4,services,health,...,4,3,2,1,1,5,2,10,9,8
25,GP,F,16,U,GT3,T,2,2,services,services,...,1,2,2,1,3,5,14,6,9,8
26,GP,M,15,U,GT3,T,2,2,other,other,...,4,2,2,1,2,5,2,12,12,11
27,GP,M,15,U,GT3,T,4,2,health,services,...,2,2,4,2,4,1,4,15,16,15
28,GP,M,16,U,LE3,A,3,4,services,other,...,5,3,3,1,1,5,4,11,11,11
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,4,4,5,5,5,5,16,10,12,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,MS,F,18,U,GT3,T,3,3,services,services,...,4,3,2,1,3,3,6,13,12,13
1015,MS,F,17,U,LE3,T,4,4,at_home,at_home,...,2,3,4,1,1,1,4,15,14,15
1016,MS,F,17,R,GT3,T,1,2,other,services,...,3,2,2,1,2,3,0,13,13,13
1017,MS,M,18,R,GT3,T,1,3,at_home,other,...,3,3,4,2,4,3,0,8,10,9
1018,MS,M,18,U,LE3,T,4,4,teacher,services,...,4,2,2,2,2,5,0,15,16,16
1019,MS,F,17,R,GT3,T,1,1,other,services,...,5,2,1,1,2,1,0,8,8,9
1020,MS,F,18,U,GT3,T,2,3,at_home,services,...,5,2,3,1,2,4,0,10,10,10
1021,MS,F,18,R,GT3,T,4,4,other,teacher,...,3,2,2,4,2,5,0,7,5,0
1022,MS,M,18,R,LE3,T,1,2,at_home,services,...,4,3,3,2,3,3,3,9,10,10
1023,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,10,11,12
1024,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,4,7,8,9
1025,MS,F,18,R,LE3,T,4,4,other,other,...,5,4,4,1,1,1,0,15,17,17
1026,MS,F,18,R,GT3,T,1,1,other,other,...,4,3,2,1,2,4,4,10,11,12
1027,MS,F,19,R,GT3,T,1,1,at_home,other,...,4,3,3,1,1,3,4,7,8,9
1028,MS,F,18,R,LE3,T,4,4,teacher,services,...,5,4,3,3,4,2,1,13,14,14
1029,MS,F,18,U,GT3,T,3,3,other,other,...,4,1,3,1,2,1,1,16,16,16
1030,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,10,8,9,9
1031,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,17,18,19
1032,MS,M,18,R,GT3,T,2,1,other,other,...,4,4,3,1,3,5,0,7,7,0
1033,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,4,14,15,16
1034,MS,M,19,R,GT3,T,1,1,other,services,...,4,3,2,1,3,5,0,5,8,0
1035,MS,M,18,R,GT3,T,4,2,other,other,...,5,4,3,4,3,3,0,7,7,0
1036,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,0,14,17,15
1037,MS,F,17,U,GT3,T,4,3,teacher,other,...,5,5,4,1,1,1,0,6,9,11
1038,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,4,4,3,2,2,5,4,7,9,10
1039,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
1040,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
1041,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
1042,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
1043,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [33]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [34]:
df=df.iloc[:,range(0,12)]
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father
5,GP,M,16,U,LE3,T,4,3,services,other,reputation,mother
6,GP,M,16,U,LE3,T,2,2,other,other,home,mother
7,GP,F,17,U,GT3,A,4,4,other,teacher,home,mother
8,GP,M,15,U,LE3,A,3,2,services,other,home,mother
9,GP,M,15,U,GT3,T,3,4,other,other,home,mother
10,GP,F,15,U,GT3,T,4,4,teacher,health,reputation,mother
11,GP,F,15,U,GT3,T,2,1,services,other,reputation,father
12,GP,M,15,U,LE3,T,4,4,health,services,course,father
13,GP,M,15,U,GT3,T,4,3,teacher,other,course,mother
14,GP,M,15,U,GT3,A,2,2,other,other,home,other
15,GP,F,16,U,GT3,T,4,4,health,other,home,mother
16,GP,F,16,U,GT3,T,4,4,services,services,reputation,mother
17,GP,F,16,U,GT3,T,3,3,other,other,reputation,mother
18,GP,M,17,U,GT3,T,3,2,services,services,course,mother
19,GP,M,16,U,LE3,T,4,3,health,other,home,father
20,GP,M,15,U,GT3,T,4,3,teacher,other,reputation,mother
21,GP,M,15,U,GT3,T,4,4,health,health,other,father
22,GP,M,16,U,LE3,T,4,2,teacher,other,course,mother
23,GP,M,16,U,LE3,T,2,2,other,other,reputation,mother
24,GP,F,15,R,GT3,T,2,4,services,health,course,mother
25,GP,F,16,U,GT3,T,2,2,services,services,home,mother
26,GP,M,15,U,GT3,T,2,2,other,other,home,mother
27,GP,M,15,U,GT3,T,4,2,health,services,other,mother
28,GP,M,16,U,LE3,A,3,4,services,other,home,mother
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,home,mother
...,...,...,...,...,...,...,...,...,...,...,...,...
1014,MS,F,18,U,GT3,T,3,3,services,services,other,mother
1015,MS,F,17,U,LE3,T,4,4,at_home,at_home,course,mother
1016,MS,F,17,R,GT3,T,1,2,other,services,course,father
1017,MS,M,18,R,GT3,T,1,3,at_home,other,course,mother
1018,MS,M,18,U,LE3,T,4,4,teacher,services,other,mother
1019,MS,F,17,R,GT3,T,1,1,other,services,reputation,mother
1020,MS,F,18,U,GT3,T,2,3,at_home,services,course,father
1021,MS,F,18,R,GT3,T,4,4,other,teacher,other,father
1022,MS,M,18,R,LE3,T,1,2,at_home,services,other,father
1023,MS,F,17,U,GT3,T,2,2,other,at_home,home,mother
1024,MS,F,17,R,GT3,T,1,2,other,other,course,mother
1025,MS,F,18,R,LE3,T,4,4,other,other,reputation,mother
1026,MS,F,18,R,GT3,T,1,1,other,other,home,mother
1027,MS,F,19,R,GT3,T,1,1,at_home,other,course,other
1028,MS,F,18,R,LE3,T,4,4,teacher,services,course,mother
1029,MS,F,18,U,GT3,T,3,3,other,other,home,mother
1030,MS,F,17,R,GT3,T,3,1,at_home,other,reputation,mother
1031,MS,M,18,U,GT3,T,4,4,teacher,teacher,home,father
1032,MS,M,18,R,GT3,T,2,1,other,other,other,mother
1033,MS,M,17,U,GT3,T,2,3,other,services,home,father
1034,MS,M,19,R,GT3,T,1,1,other,services,other,mother
1035,MS,M,18,R,GT3,T,4,2,other,other,home,father
1036,MS,F,18,R,GT3,T,2,2,at_home,other,other,mother
1037,MS,F,17,U,GT3,T,4,3,teacher,other,other,mother
1038,MS,F,18,R,GT3,T,4,4,teacher,at_home,reputation,mother
1039,MS,F,19,R,GT3,T,2,3,services,other,course,mother
1040,MS,F,18,U,LE3,T,3,1,teacher,services,course,mother
1041,MS,F,18,U,GT3,T,1,1,other,other,course,mother
1042,MS,M,17,U,LE3,T,3,1,services,services,course,mother
1043,MS,M,18,R,LE3,T,3,2,services,other,course,mother

### Step 5. Create a lambda function that captalize strings.

In [35]:
lambda x:x.capitalize()

### Step 6. Capitalize both Mjob and Fjob

In [36]:
df.Mjob.apply(lambda x:x.capitalize())

0        At_home
1        At_home
2        At_home
3         Health
4          Other
5       Services
6          Other
7          Other
8       Services
9          Other
10       Teacher
11      Services
12        Health
13       Teacher
14         Other
15        Health
16      Services
17         Other
18      Services
19        Health
20       Teacher
21        Health
22       Teacher
23         Other
24      Services
25      Services
26         Other
27        Health
28      Services
29       Teacher
          ...
1014    Services
1015     At_home
1016       Other
1017     At_home
1018     Teacher
1019       Other
1020     At_home
1021       Other
1022     At_home
1023       Other
1024       Other
1025       Other
1026       Other
1027     At_home
1028     Teacher
1029       Other
1030     At_home
1031     Teacher
1032       Other
1033       Other
1034       Other
1035       Other
1036     At_home
1037     Teacher
1038     Teacher
1039    Services
1040     Teacher
1041       Other
1042    Services
1043    Services
Name: Mjob, Length: 1044, dtype: object

In [37]:
df.Fjob.apply(lambda x:x.capitalize())

0        Teacher
1          Other
2          Other
3       Services
4          Other
5          Other
6          Other
7        Teacher
8          Other
9          Other
10        Health
11         Other
12      Services
13         Other
14         Other
15         Other
16      Services
17         Other
18      Services
19         Other
20         Other
21        Health
22         Other
23         Other
24        Health
25      Services
26         Other
27      Services
28         Other
29       Teacher
          ...
1014    Services
1015     At_home
1016    Services
1017       Other
1018    Services
1019    Services
1020    Services
1021     Teacher
1022    Services
1023     At_home
1024       Other
1025       Other
1026       Other
1027       Other
1028    Services
1029       Other
1030       Other
1031     Teacher
1032       Other
1033    Services
1034    Services
1035       Other
1036       Other
1037       Other
1038     At_home
1039       Other
1040    Services
1041       Other
1042    Services
1043       Other
Name: Fjob, Length: 1044, dtype: object

### Step 7. Print the last elements of the data set.

In [38]:
df.Mjob.iloc[-1]

'services'

In [39]:
df.Fjob.iloc[-1]

'other'

In [40]:
df.tail(1)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
1043,MS,M,18,R,LE3,T,3,2,services,other,course,mother

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and captalize Mjob and Fjob.

In [41]:
df["Mjob"]=df.Mjob.apply(lambda x:x.capitalize())
df["Fjob"]=df.Fjob.apply(lambda x:x.capitalize())
df.head()

C:\Users\intel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\intel\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,At_home,Other,course,father
2,GP,F,15,U,LE3,T,1,1,At_home,Other,other,mother
3,GP,F,15,U,GT3,T,4,2,Health,Services,home,mother
4,GP,F,16,U,GT3,T,3,3,Other,Other,home,father

### Step 9. Create a function called majority that return a boolean value to a new column called legal_drinker

In [44]:
def majority(ser):
    '''
    This method take age column of dataframe as input and return series of booleans on the basis that 
    if age is greater or equal to 18 then person is legal drinker and it's corresponding value of legal_drinker column is 
    1(True) and if person is less than 18 then person is not legal drinker and it's corresponding value of legal_drinker column
    is 0(False). 
    '''
    if(isinstance(ser, pd.Series)):
        legal_drinker=[]
        for i in ser:
            if(i>=18):
                legal_drinker.append(1)
            else:
                legal_drinker.append(0)
        return pd.Series(legal_drinker)
    else:
        print("Please enter series or dataframe column.")

In [45]:
df["legal_drinker"]=majority(df.age)
df

C:\Users\intel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,mother,1
1,GP,F,17,U,GT3,T,1,1,At_home,Other,course,father,0
2,GP,F,15,U,LE3,T,1,1,At_home,Other,other,mother,0
3,GP,F,15,U,GT3,T,4,2,Health,Services,home,mother,0
4,GP,F,16,U,GT3,T,3,3,Other,Other,home,father,0
5,GP,M,16,U,LE3,T,4,3,Services,Other,reputation,mother,0
6,GP,M,16,U,LE3,T,2,2,Other,Other,home,mother,0
7,GP,F,17,U,GT3,A,4,4,Other,Teacher,home,mother,0
8,GP,M,15,U,LE3,A,3,2,Services,Other,home,mother,0
9,GP,M,15,U,GT3,T,3,4,Other,Other,home,mother,0
10,GP,F,15,U,GT3,T,4,4,Teacher,Health,reputation,mother,0
11,GP,F,15,U,GT3,T,2,1,Services,Other,reputation,father,0
12,GP,M,15,U,LE3,T,4,4,Health,Services,course,father,0
13,GP,M,15,U,GT3,T,4,3,Teacher,Other,course,mother,0
14,GP,M,15,U,GT3,A,2,2,Other,Other,home,other,0
15,GP,F,16,U,GT3,T,4,4,Health,Other,home,mother,0
16,GP,F,16,U,GT3,T,4,4,Services,Services,reputation,mother,0
17,GP,F,16,U,GT3,T,3,3,Other,Other,reputation,mother,0
18,GP,M,17,U,GT3,T,3,2,Services,Services,course,mother,0
19,GP,M,16,U,LE3,T,4,3,Health,Other,home,father,0
20,GP,M,15,U,GT3,T,4,3,Teacher,Other,reputation,mother,0
21,GP,M,15,U,GT3,T,4,4,Health,Health,other,father,0
22,GP,M,16,U,LE3,T,4,2,Teacher,Other,course,mother,0
23,GP,M,16,U,LE3,T,2,2,Other,Other,reputation,mother,0
24,GP,F,15,R,GT3,T,2,4,Services,Health,course,mother,0
25,GP,F,16,U,GT3,T,2,2,Services,Services,home,mother,0
26,GP,M,15,U,GT3,T,2,2,Other,Other,home,mother,0
27,GP,M,15,U,GT3,T,4,2,Health,Services,other,mother,0
28,GP,M,16,U,LE3,A,3,4,Services,Other,home,mother,0
29,GP,M,16,U,GT3,T,4,4,Teacher,Teacher,home,mother,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,MS,F,18,U,GT3,T,3,3,Services,Services,other,mother,1
1015,MS,F,17,U,LE3,T,4,4,At_home,At_home,course,mother,0
1016,MS,F,17,R,GT3,T,1,2,Other,Services,course,father,0
1017,MS,M,18,R,GT3,T,1,3,At_home,Other,course,mother,1
1018,MS,M,18,U,LE3,T,4,4,Teacher,Services,other,mother,1
1019,MS,F,17,R,GT3,T,1,1,Other,Services,reputation,mother,0
1020,MS,F,18,U,GT3,T,2,3,At_home,Services,course,father,1
1021,MS,F,18,R,GT3,T,4,4,Other,Teacher,other,father,1
1022,MS,M,18,R,LE3,T,1,2,At_home,Services,other,father,1
1023,MS,F,17,U,GT3,T,2,2,Other,At_home,home,mother,0
1024,MS,F,17,R,GT3,T,1,2,Other,Other,course,mother,0
1025,MS,F,18,R,LE3,T,4,4,Other,Other,reputation,mother,1
1026,MS,F,18,R,GT3,T,1,1,Other,Other,home,mother,1
1027,MS,F,19,R,GT3,T,1,1,At_home,Other,course,other,1
1028,MS,F,18,R,LE3,T,4,4,Teacher,Services,course,mother,1
1029,MS,F,18,U,GT3,T,3,3,Other,Other,home,mother,1
1030,MS,F,17,R,GT3,T,3,1,At_home,Other,reputation,mother,0
1031,MS,M,18,U,GT3,T,4,4,Teacher,Teacher,home,father,1
1032,MS,M,18,R,GT3,T,2,1,Other,Other,other,mother,1
1033,MS,M,17,U,GT3,T,2,3,Other,Services,home,father,0
1034,MS,M,19,R,GT3,T,1,1,Other,Services,other,mother,1
1035,MS,M,18,R,GT3,T,4,2,Other,Other,home,father,1
1036,MS,F,18,R,GT3,T,2,2,At_home,Other,other,mother,1
1037,MS,F,17,U,GT3,T,4,3,Teacher,Other,other,mother,0
1038,MS,F,18,R,GT3,T,4,4,Teacher,At_home,reputation,mother,1
1039,MS,F,19,R,GT3,T,2,3,Services,Other,course,mother,1
1040,MS,F,18,U,LE3,T,3,1,Teacher,Services,course,mother,1
1041,MS,F,18,U,GT3,T,1,1,Other,Other,course,mother,1
1042,MS,M,17,U,LE3,T,3,1,Services,Services,course,mother,0
1043,MS,M,18,R,LE3,T,3,2,Services,Other,course,mother,1

### Step 10. Multiply every number of the dataset by 10.

In [50]:
def multiplyNumberByTen(num):
    if(num.dtype=="int64"):
        return (num*10)
    else:
        return num

In [51]:
df.apply(multiplyNumberByTen)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,180,U,GT3,A,40,40,At_home,Teacher,course,mother,10
1,GP,F,170,U,GT3,T,10,10,At_home,Other,course,father,0
2,GP,F,150,U,LE3,T,10,10,At_home,Other,other,mother,0
3,GP,F,150,U,GT3,T,40,20,Health,Services,home,mother,0
4,GP,F,160,U,GT3,T,30,30,Other,Other,home,father,0
5,GP,M,160,U,LE3,T,40,30,Services,Other,reputation,mother,0
6,GP,M,160,U,LE3,T,20,20,Other,Other,home,mother,0
7,GP,F,170,U,GT3,A,40,40,Other,Teacher,home,mother,0
8,GP,M,150,U,LE3,A,30,20,Services,Other,home,mother,0
9,GP,M,150,U,GT3,T,30,40,Other,Other,home,mother,0
10,GP,F,150,U,GT3,T,40,40,Teacher,Health,reputation,mother,0
11,GP,F,150,U,GT3,T,20,10,Services,Other,reputation,father,0
12,GP,M,150,U,LE3,T,40,40,Health,Services,course,father,0
13,GP,M,150,U,GT3,T,40,30,Teacher,Other,course,mother,0
14,GP,M,150,U,GT3,A,20,20,Other,Other,home,other,0
15,GP,F,160,U,GT3,T,40,40,Health,Other,home,mother,0
16,GP,F,160,U,GT3,T,40,40,Services,Services,reputation,mother,0
17,GP,F,160,U,GT3,T,30,30,Other,Other,reputation,mother,0
18,GP,M,170,U,GT3,T,30,20,Services,Services,course,mother,0
19,GP,M,160,U,LE3,T,40,30,Health,Other,home,father,0
20,GP,M,150,U,GT3,T,40,30,Teacher,Other,reputation,mother,0
21,GP,M,150,U,GT3,T,40,40,Health,Health,other,father,0
22,GP,M,160,U,LE3,T,40,20,Teacher,Other,course,mother,0
23,GP,M,160,U,LE3,T,20,20,Other,Other,reputation,mother,0
24,GP,F,150,R,GT3,T,20,40,Services,Health,course,mother,0
25,GP,F,160,U,GT3,T,20,20,Services,Services,home,mother,0
26,GP,M,150,U,GT3,T,20,20,Other,Other,home,mother,0
27,GP,M,150,U,GT3,T,40,20,Health,Services,other,mother,0
28,GP,M,160,U,LE3,A,30,40,Services,Other,home,mother,0
29,GP,M,160,U,GT3,T,40,40,Teacher,Teacher,home,mother,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,MS,F,180,U,GT3,T,30,30,Services,Services,other,mother,10
1015,MS,F,170,U,LE3,T,40,40,At_home,At_home,course,mother,0
1016,MS,F,170,R,GT3,T,10,20,Other,Services,course,father,0
1017,MS,M,180,R,GT3,T,10,30,At_home,Other,course,mother,10
1018,MS,M,180,U,LE3,T,40,40,Teacher,Services,other,mother,10
1019,MS,F,170,R,GT3,T,10,10,Other,Services,reputation,mother,0
1020,MS,F,180,U,GT3,T,20,30,At_home,Services,course,father,10
1021,MS,F,180,R,GT3,T,40,40,Other,Teacher,other,father,10
1022,MS,M,180,R,LE3,T,10,20,At_home,Services,other,father,10
1023,MS,F,170,U,GT3,T,20,20,Other,At_home,home,mother,0
1024,MS,F,170,R,GT3,T,10,20,Other,Other,course,mother,0
1025,MS,F,180,R,LE3,T,40,40,Other,Other,reputation,mother,10
1026,MS,F,180,R,GT3,T,10,10,Other,Other,home,mother,10
1027,MS,F,190,R,GT3,T,10,10,At_home,Other,course,other,10
1028,MS,F,180,R,LE3,T,40,40,Teacher,Services,course,mother,10
1029,MS,F,180,U,GT3,T,30,30,Other,Other,home,mother,10
1030,MS,F,170,R,GT3,T,30,10,At_home,Other,reputation,mother,0
1031,MS,M,180,U,GT3,T,40,40,Teacher,Teacher,home,father,10
1032,MS,M,180,R,GT3,T,20,10,Other,Other,other,mother,10
1033,MS,M,170,U,GT3,T,20,30,Other,Services,home,father,0
1034,MS,M,190,R,GT3,T,10,10,Other,Services,other,mother,10
1035,MS,M,180,R,GT3,T,40,20,Other,Other,home,father,10
1036,MS,F,180,R,GT3,T,20,20,At_home,Other,other,mother,10
1037,MS,F,170,U,GT3,T,40,30,Teacher,Other,other,mother,0
1038,MS,F,180,R,GT3,T,40,40,Teacher,At_home,reputation,mother,10
1039,MS,F,190,R,GT3,T,20,30,Services,Other,course,mother,10
1040,MS,F,180,U,LE3,T,30,10,Teacher,Services,course,mother,10
1041,MS,F,180,U,GT3,T,10,10,Other,Other,course,mother,10
1042,MS,M,170,U,LE3,T,30,10,Services,Services,course,mother,0
1043,MS,M,180,R,LE3,T,30,20,Services,Other,course,mother,10